from src.db.crud.user import (
    get_user_by_id,
    get_user_by_phone,
    get_user_by_email,
    create_user,
    create_user_profile,
    update_user_login_time,
)
from src.db.crud.pet import (
    get_pet_by_id,
    get_pets_by_user,
    create_pet,
    update_pet,
    delete_pet,
)
# [DEPRECATED] Conversation CRUD - use MongoDB repositories instead
# from src.db.crud.conversation import (
#     get_conversation_by_id,
#     get_user_conversations,
#     create_conversation,
#     update_conversation,
#     delete_conversation,
#     get_message_by_id,
#     get_conversation_messages,
#     create_message,
#     update_message_vector_id,
#     get_recent_messages,
# )
from src.db.crud.health import (
    create_health_record,
    get_health_record_by_id,
    get_health_records_by_pet,
    delete_health_record,
    create_consultation,
    get_consultation_by_id,
    get_user_consultations,
    get_pet_consultations,
    update_consultation_result,
)
from src.db.crud.behavior import (
    create_behavior_analysis,
    get_behavior_analysis_by_id,
    get_user_behavior_analyses,
    get_pet_behavior_analyses,
    update_behavior_analysis_result,
)

__all__ = [
    "get_user_by_id",
    "get_user_by_phone",
    "get_user_by_email",
    "create_user",
    "create_user_profile",
    "update_user_login_time",
    "get_pet_by_id",
    "get_pets_by_user",
    "create_pet",
    "update_pet",
    "delete_pet",
    # DEPRECATED: Use ConversationRepository and MessageRepository from MongoDB
    # "get_conversation_by_id",
    # "get_user_conversations",
    # "create_conversation",
    # "update_conversation",
    # "delete_conversation",
    # "get_message_by_id",
    # "get_conversation_messages",
    # "create_message",
    # "update_message_vector_id",
    # "get_recent_messages",
    "create_health_record",
    "get_health_record_by_id",
    "get_health_records_by_pet",
    "delete_health_record",
    "create_consultation",
    "get_consultation_by_id",
    "get_user_consultations",
    "get_pet_consultations",
    "update_consultation_result",
    "create_behavior_analysis",
    "get_behavior_analysis_by_id",
    "get_user_behavior_analyses",
    "get_pet_behavior_analyses",
    "update_behavior_analysis_result",
]
